import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#09090b]">
        {/* React Hot Toast Global Provider */}
        <Toaster
          position="top-center"
          toastOptions={{
            // Sets default visibility to exactly 3 seconds (3000 milliseconds)
            duration: 3000,
            
            // Customizing hot-toast to perfectly match your Dark + Green Glow Theme
            style: {
              background: "#121214",
              color: "#e4e4e7",
              border: "1px solid rgba(63, 63, 70, 0.4)",
              marginTop: "4.5rem", // Pushes the toast right below your sticky navbar
              zIndex: 99999, // Ensures it stays above all elements
            },
            success: {
              iconTheme: {
                primary: "#10b981",
                secondary: "#121214",
              },
            },
          }}
        />

        <Navbar />

        <main className="flex-1">{children}</main>
        
        <Footer />
      </body>
    </html>
  );
}